/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DialogueEffectsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// parser.ts
var BRACKET_ESCAPES = /* @__PURE__ */ new Set(["\\[", "\\]", "\\{", "\\}"]);
var SENTIMENT_RE = /^([A-Za-z][\w' -]*)\{([\w]+)\}:\s?/;
function parseLine(line) {
  let speaker = null;
  let sentiment = null;
  let body = line;
  const sent = SENTIMENT_RE.exec(line);
  if (sent) {
    speaker = sent[1];
    sentiment = sent[2];
    body = line.slice(sent[0].length);
  }
  return { speaker, sentiment, segments: parseSegments(body) };
}
function parseSegments(text) {
  const segments = [];
  let i = 0;
  let buffer = "";
  const flush = () => {
    if (buffer) {
      segments.push({ kind: "text", text: buffer });
      buffer = "";
    }
  };
  while (i < text.length) {
    const ch = text[i];
    if (ch === "\\" && i + 1 < text.length && BRACKET_ESCAPES.has(text.slice(i, i + 2))) {
      flush();
      segments.push({ kind: "escape", char: text[i + 1] });
      i += 2;
      continue;
    }
    if (ch === "[") {
      const inline = tryParseInline(text, i);
      if (inline) {
        flush();
        segments.push(inline);
        i = inline.end;
        continue;
      }
    }
    if (ch === "{") {
      const standalone = tryParseStandalone(text, i);
      if (standalone) {
        flush();
        segments.push(standalone);
        i = standalone.end;
        continue;
      }
    }
    buffer += ch;
    i++;
  }
  flush();
  return segments;
}
function tryParseInline(text, start) {
  for (let j = start + 1; j < text.length; j++) {
    if (text[j] === "]") {
      if (j + 1 < text.length && text[j + 1] === "{") {
        const close = text.indexOf("}", j + 2);
        if (close === -1)
          return null;
        const inner = text.slice(start + 1, j);
        const effStr = text.slice(j + 2, close);
        const effects = parseEffects(effStr);
        return { kind: "inline", text: inner, effects, end: close + 1 };
      }
      return null;
    }
  }
  return null;
}
function tryParseStandalone(text, start) {
  const close = text.indexOf("}", start + 1);
  if (close === -1)
    return null;
  const inner = text.slice(start + 1, close);
  const eq = inner.indexOf("=");
  if (eq === -1)
    return null;
  const key = inner.slice(0, eq).trim();
  const value = inner.slice(eq + 1).trim();
  if (!key)
    return null;
  return { kind: "standalone", key, value, end: close + 1 };
}
function parseEffects(raw) {
  const pairs = [];
  for (const part of raw.split(",")) {
    const eq = part.indexOf("=");
    if (eq === -1) {
      const key2 = part.trim();
      if (key2)
        pairs.push({ key: key2, value: "" });
      continue;
    }
    const key = part.slice(0, eq).trim();
    const value = part.slice(eq + 1).trim();
    if (key)
      pairs.push({ key, value });
  }
  return pairs;
}
function isConditional(key, value) {
  const k = key.toLowerCase();
  if (k === "requires" || k === "sets" || k === "onclear" || k === "trigger")
    return true;
  return /=true|=false/i.test(value);
}
var INLINE_EFFECTS = [
  { key: "text_effect", value: "shake" },
  { key: "text_effect", value: "wave" },
  { key: "text_effect", value: "dangle" },
  { key: "text_effect", value: "bounce" },
  { key: "text_effect", value: "swing" },
  { key: "text_effect", value: "rainbow" },
  { key: "text_effect", value: "fade" },
  { key: "text_effect", value: "bold" },
  { key: "text_effect", value: "italic" },
  { key: "color", value: "red" },
  { key: "color", value: "#ff6644" },
  { key: "font_size", value: "0.8" }
];
var STANDALONE_EFFECTS = [
  { key: "text_speed", value: "0.5" },
  { key: "sfx", value: '"whisper"' },
  { key: "effect", value: "screen_shake" },
  { key: "effect", value: "camera_zoom" },
  { key: "effect", value: "flash" },
  { key: "custom_action", value: "1" }
];
var SENTIMENTS = [
  "neutral",
  "happy",
  "sad",
  "angry",
  "excited",
  "surprised",
  "whispering"
];

// main.ts
var DEFAULT_SETTINGS = {
  animateInPreview: false,
  showStandalonePills: true,
  showSentimentChips: true
};
var INLINE_CHOICES = INLINE_EFFECTS.map((pair) => ({
  pair,
  label: `${pair.key}=${pair.value}`
}));
var STANDALONE_CHOICES = STANDALONE_EFFECTS.map((pair) => ({
  pair,
  label: `{${pair.key}=${pair.value}}`
}));
var DialogueEffectsPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.addSettingTab(new DialogueEffectsSettingTab(this.app, this));
    this.registerMarkdownPostProcessor((el, ctx) => {
      if (ctx.sourcePath) {
        this.renderPreview(el);
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        this.buildContextMenu(menu, editor);
      })
    );
    this.addCommand({
      id: "insert-inline-effect",
      name: "Insert effect on selected text",
      editorCallback: (editor) => {
        this.chooseEffect(editor, INLINE_CHOICES, (choice) => {
          this.wrapSelection(editor, choice.pair);
        });
      }
    });
    this.addCommand({
      id: "insert-standalone-effect",
      name: "Insert standalone effect at cursor",
      editorCallback: (editor) => {
        this.chooseEffect(editor, STANDALONE_CHOICES, (choice) => {
          editor.replaceSelection(`{${choice.pair.key}=${choice.pair.value}}`);
        });
      }
    });
    this.addCommand({
      id: "tag-sentiment",
      name: "Tag current line with a sentiment",
      editorCallback: (editor) => {
        this.chooseSentiment(editor);
      }
    });
    this.addRibbonIcon("wand-2", "Dialogue Effects", () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (!view) {
        new import_obsidian.Notice("No active markdown editor");
        return;
      }
      this.chooseEffect(view.editor, INLINE_CHOICES, (choice) => {
        this.wrapSelection(view.editor, choice.pair);
      });
    });
  }
  onunload() {
  }
  // ------------------------------------------------------------------
  // Preview rendering
  // ------------------------------------------------------------------
  /**
   * Walk the rendered element, find text nodes that belong to dialogue
   * content, and replace annotation spans with styled HTML.
   *
   * We only touch text nodes inside paragraphs (not headings, code, or
   * links), and we skip nodes that are already inside our own rendered
   * output to avoid double-processing on re-render.
   */
  renderPreview(el) {
    var _a;
    const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) {
      const node = walker.currentNode;
      if (!node.parentElement)
        continue;
      if (node.parentElement.closest("code, pre, a.dte-processed"))
        continue;
      nodes.push(node);
    }
    for (const node of nodes) {
      const text = (_a = node.textContent) != null ? _a : "";
      if (!text.trim())
        continue;
      if (!/^(?:[A-Za-z][\w' -]*\{[\w]+\}:|.*[\[\]{].*)/.test(text))
        continue;
      const parsed = parseLine(text);
      const hasAnnotations = parsed.segments.some(
        (seg) => seg.kind === "inline" || seg.kind === "standalone" || seg.kind === "escape"
      );
      if (!parsed.sentiment && !hasAnnotations)
        continue;
      const span = document.createElement("span");
      span.addClass("dte-processed");
      if (parsed.speaker) {
        const speaker = span.createSpan({ cls: "dte-speaker" });
        speaker.textContent = parsed.speaker;
        if (parsed.sentiment && this.settings.showSentimentChips) {
          const tag = span.createSpan({ cls: "dte-sentiment", text: parsed.sentiment });
          tag.setAttribute("title", `portrait: ${parsed.sentiment}`);
        }
        span.appendText(": ");
      }
      for (const seg of parsed.segments) {
        span.appendChild(this.renderSegment(seg));
      }
      node.replaceWith(span);
    }
  }
  renderSegment(seg) {
    const span = document.createElement("span");
    switch (seg.kind) {
      case "text":
        span.textContent = seg.text;
        break;
      case "escape":
        span.textContent = seg.char;
        break;
      case "inline": {
        span.addClass("dte-inline");
        span.setAttribute("title", this.effectTitle(seg.effects));
        const inner = document.createElement("span");
        inner.textContent = seg.text;
        span.appendChild(inner);
        for (const eff of seg.effects) {
          this.applyInlineEffect(span, eff);
        }
        break;
      }
      case "standalone": {
        if (isConditional(seg.key, seg.value)) {
          span.addClass("dte-conditional");
          span.textContent = `{${seg.key}=${seg.value}}`;
        } else {
          span.addClass("dte-standalone");
          span.setAttribute("title", `fires at this point: ${seg.key}=${seg.value}`);
          if (this.settings.showStandalonePills) {
            span.textContent = `{${seg.key}=${seg.value}}`;
          } else {
            span.classList.remove("dte-standalone");
            span.addClass("dte-effect-hint");
            span.textContent = seg.key === "sfx" ? "\u266A" : "\xBB";
          }
        }
        break;
      }
    }
    return span;
  }
  effectTitle(effects) {
    return effects.map((e) => `${e.key}=${e.value}`).join(", ");
  }
  /** Map an inline effect pair to visual styling on the span. */
  applyInlineEffect(span, eff) {
    const { key, value } = eff;
    switch (key) {
      case "color":
        span.style.color = value;
        span.style.fontWeight = "inherit";
        break;
      case "font_size": {
        const scale = parseFloat(value);
        if (isFinite(scale))
          span.style.fontSize = `${scale}em`;
        break;
      }
      case "text_effect":
        switch (value) {
          case "bold":
            span.style.fontWeight = "bold";
            break;
          case "italic":
            span.style.fontStyle = "italic";
            break;
          case "shake":
            if (this.settings.animateInPreview)
              span.addClass("dte-anim-shake");
            else
              span.addClass("dte-effect-hint");
            break;
          case "wave":
          case "swing":
            if (this.settings.animateInPreview)
              span.addClass("dte-anim-wave");
            else
              span.addClass("dte-effect-hint");
            break;
          case "dangle":
          case "pendulum":
            if (this.settings.animateInPreview)
              span.addClass("dte-anim-dangle");
            else
              span.addClass("dte-effect-hint");
            break;
          case "bounce":
            if (this.settings.animateInPreview)
              span.addClass("dte-anim-bounce");
            else
              span.addClass("dte-effect-hint");
            break;
          case "rainbow":
            if (this.settings.animateInPreview)
              span.addClass("dte-anim-rainbow");
            else
              span.addClass("dte-effect-hint");
            break;
          case "fade":
            if (this.settings.animateInPreview)
              span.addClass("dte-anim-fade");
            else
              span.addClass("dte-effect-hint");
            break;
          default:
            span.addClass("dte-unknown-effect");
        }
        break;
    }
  }
  // ------------------------------------------------------------------
  // Insert / tag tooling
  // ------------------------------------------------------------------
  // ------------------------------------------------------------------
  // Context menu (right-click in the editor)
  // ------------------------------------------------------------------
  buildContextMenu(menu, editor) {
    const hasSelection = editor.getSelection().length > 0;
    const lineText = editor.getLine(editor.getCursor().line);
    const hasSpeaker = /^(?:[A-Za-z][\w' -]*|[A-Za-z][\w' -]*\s*\([^)]*\))\s*:/.test(lineText);
    menu.addItem((item) => {
      item.setTitle(hasSelection ? "Annotate selection with effect" : "Wrap word with effect").setIcon("wand-2").onClick(() => {
        this.chooseEffect(editor, INLINE_CHOICES, (choice) => {
          this.wrapSelection(editor, choice.pair);
        });
      });
    });
    menu.addItem((item) => {
      item.setTitle("Insert standalone effect at cursor").setIcon("plus-circle").onClick(() => {
        this.chooseEffect(editor, STANDALONE_CHOICES, (choice) => {
          editor.replaceSelection(`{${choice.pair.key}=${choice.pair.value}}`);
        });
      });
    });
    if (hasSpeaker) {
      menu.addItem((item) => {
        item.setTitle("Tag speaker sentiment").setIcon("smile").onClick(() => {
          this.chooseSentiment(editor);
        });
      });
    }
  }
  chooseEffect(editor, choices, onPick) {
    new EffectSuggestModal(this.app, choices, onPick).open();
  }
  chooseSentiment(editor) {
    new SentimentSuggestModal(this.app, editor).open();
  }
  /** Wrap the current selection as [text]{effect=value}; value is left selected for easy editing. */
  wrapSelection(editor, pair) {
    const selection = editor.getSelection();
    const text = selection || "text";
    const effStr = pair.value ? `${pair.key}=${pair.value}` : pair.key;
    const replacement = `[${text}]{${effStr}}`;
    const anchor = editor.getCursor("from");
    const head = editor.getCursor("to");
    editor.replaceSelection(replacement);
    if (selection) {
      const line = anchor.line;
      const valueStart = anchor.ch + text.length + 3;
      editor.setSelection(
        { line, ch: valueStart },
        { line, ch: valueStart + pair.value.length }
      );
    }
  }
};
var EffectSuggestModal = class extends import_obsidian.SuggestModal {
  constructor(app, choices, onPick) {
    super(app);
    this.choices = choices;
    this.onPick = onPick;
    this.setPlaceholder("Pick an effect");
    this.limit = 20;
  }
  getSuggestions(_query) {
    const q = _query.trim().toLowerCase();
    if (!q)
      return this.choices;
    return this.choices.filter((c) => c.label.toLowerCase().includes(q));
  }
  renderSuggestion(choice, el) {
    el.createDiv({ text: choice.label });
  }
  onChooseSuggestion(choice, _evt) {
    this.onPick(choice);
  }
};
var SentimentSuggestModal = class extends import_obsidian.SuggestModal {
  constructor(app, editor) {
    super(app);
    this.editor = editor;
    this.setPlaceholder("Pick a sentiment");
    this.limit = 20;
  }
  getSuggestions(query) {
    const q = query.trim().toLowerCase();
    if (!q)
      return SENTIMENTS;
    return SENTIMENTS.filter((s) => s.toLowerCase().includes(q));
  }
  renderSuggestion(sentiment, el) {
    el.createDiv({ text: sentiment });
  }
  onChooseSuggestion(sentiment, _evt) {
    const editor = this.editor;
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    const m = /^(?:([A-Za-z][\w' -]*)|([A-Za-z][\w' -]*)\s*\([^)]*\))\s*:/g.exec(lineText);
    if (!m) {
      new import_obsidian.Notice("No speaker name at the start of this line");
      return;
    }
    const name = m[1] || m[2];
    const insertAt = lineText.indexOf(":");
    editor.replaceRange(`{${sentiment}}`, { line: cursor.line, ch: insertAt }, {
      line: cursor.line,
      ch: insertAt
    });
    editor.setCursor({ line: cursor.line, ch: insertAt + sentiment.length + 2 });
  }
};
var DialogueEffectsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Dialogue Effects" });
    containerEl.createEl("p", {
      text: "Preview rendering for dialogue annotations. The stored text is never changed; this only styles what you see in Obsidian."
    });
    new import_obsidian.Setting(containerEl).setName("Animate effects in preview").setDesc("Move shake, wave, bounce and the other behaviors. Off by default so reading stays calm.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.animateInPreview).onChange(async (value) => {
        this.plugin.settings.animateInPreview = value;
        await this.plugin.saveData(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show standalone effect pills").setDesc('Show {sfx="..."}, {text_speed=0.5} and friends as small pill markers. Off shows a single subtle dot instead.').addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showStandalonePills).onChange(async (value) => {
        this.plugin.settings.showStandalonePills = value;
        await this.plugin.saveData(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show sentiment chips").setDesc("Show Name{sentiment} as a small chip after the speaker name.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showSentimentChips).onChange(async (value) => {
        this.plugin.settings.showSentimentChips = value;
        await this.plugin.saveData(this.plugin.settings);
      })
    );
    containerEl.createEl("h3", { text: "Right-click menu" });
    new import_obsidian.Setting(containerEl).setName("Select text, right-click").setDesc("Annotate selection \u2014 wraps [text]{effect}. Insert standalone \u2014 adds {key=value} at cursor. On a speaker line, tag sentiment \u2014 adds Name{sentiment}.");
  }
};
