/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FlagRegistryPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var os = __toESM(require("os"));
var DEFAULT_SETTINGS = {
  unityAssetPath: path.join(
    os.homedir(),
    "UnityProjects/TheRoadAhead/Assets/ScriptableObjects/DataRegistries/FlagRegistry.asset"
  ),
  pythonBin: "python3"
};
function runScript(script, args) {
  return new Promise((resolve, reject) => {
    (0, import_child_process.execFile)(
      script,
      args,
      { maxBuffer: 1024 * 1024 * 8, timeout: 12e4 },
      (err, stdout, stderr) => {
        if (err) {
          reject(new Error(stderr || err.message));
        } else {
          resolve(stdout);
        }
      }
    );
  });
}
var ResultModal = class extends import_obsidian.Modal {
  constructor(app, title, content) {
    super(app);
    this.title = title;
    this.content = content;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.title });
    const pre = contentEl.createEl("pre");
    pre.style.whiteSpace = "pre-wrap";
    pre.style.maxHeight = "70vh";
    pre.style.overflowY = "auto";
    pre.style.fontSize = "12px";
    pre.style.fontFamily = "var(--font-monospace)";
    pre.setText(this.content);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var FlagRegistryPlugin = class extends import_obsidian.Plugin {
  constructor(app, manifest) {
    super(app, manifest);
    this.scriptsDir = path.join(manifest.dir || "", "scripts");
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("flag", "Flag Registry", () => {
      this.runScan();
    });
    this.addCommand({
      id: "flag-registry-scan",
      name: "Run flag scan (update master-registry.md)",
      callback: () => this.runScan()
    });
    this.addCommand({
      id: "flag-registry-open-registry",
      name: "Open master-registry.md",
      callback: () => this.openRegistry()
    });
    this.addCommand({
      id: "flag-registry-compare",
      name: "Compare Obsidian registry vs Unity FlagRegistry",
      callback: () => this.runComparison()
    });
    this.addSettingTab(new FlagRegistrySettingTab(this.app, this));
  }
  onunload() {
  }
  // -------- actions --------
  vaultPath() {
    var _a, _b, _c;
    return (_c = (_b = (_a = this.app.vault.adapter).getBasePath) == null ? void 0 : _b.call(_a)) != null ? _c : this.app.vault.getRoot().path;
  }
  scanScript() {
    return path.join(this.scriptsDir, "scan_flags.py");
  }
  compareScript() {
    return path.join(this.scriptsDir, "compare_flags.py");
  }
  async runScan() {
    new import_obsidian.Notice("Flag Registry: scanning vault\u2026");
    try {
      const vault = this.vaultPath();
      const stdout = await runScript(this.settings.pythonBin, [
        this.scanScript(),
        vault
      ]);
      new import_obsidian.Notice("Flag Registry: scan complete");
      console.log(`[flag-registry] scan stdout:
${stdout}`);
      await this.openRegistry();
    } catch (err) {
      console.error("[flag-registry] scan failed", err);
      new import_obsidian.Notice(`Flag Registry: scan failed \u2014 ${err.message}`, 8e3);
    }
  }
  async openRegistry() {
    const vault = this.vaultPath();
    const registryPath = path.join(vault, "master-registry.md");
    const file = this.app.vault.getAbstractFileByPath("master-registry.md");
    if (file instanceof import_obsidian.TFile) {
      await this.app.workspace.getLeaf(false).openFile(file);
    } else {
      new import_obsidian.Notice(`Flag Registry: master-registry.md not found. Run the scan first.`, 8e3);
    }
  }
  async runComparison() {
    new import_obsidian.Notice("Flag Registry: comparing registries\u2026");
    try {
      const vault = this.vaultPath();
      const stdout = await runScript(this.settings.pythonBin, [
        this.compareScript(),
        vault,
        "--unity-asset",
        this.settings.unityAssetPath
      ]);
      new ResultModal(this.app, "Flag Registry Comparison", stdout).open();
    } catch (err) {
      console.error("[flag-registry] comparison failed", err);
      new import_obsidian.Notice(`Flag Registry: comparison failed \u2014 ${err.message}`, 8e3);
    }
  }
  // -------- settings --------
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var FlagRegistrySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Flag Registry" });
    new import_obsidian.Setting(containerEl).setName("Unity FlagRegistry asset").setDesc("Path to the Unity FlagRegistry.asset used by the comparison tool.").addText(
      (text) => text.setPlaceholder("/path/to/FlagRegistry.asset").setValue(this.plugin.settings.unityAssetPath).onChange(async (value) => {
        this.plugin.settings.unityAssetPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Python binary").setDesc("Command used to invoke the bundled Python scripts (python3 or a venv path).").addText(
      (text) => text.setPlaceholder("python3").setValue(this.plugin.settings.pythonBin).onChange(async (value) => {
        this.plugin.settings.pythonBin = value || "python3";
        await this.plugin.saveSettings();
      })
    );
  }
};
