/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DialoguePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var DEFAULT_SETTINGS = {
  templatePath: "1.1 Admin/Resources/Templates/Dialogue Template.md",
  dialogueFolderName: "Dialogues"
};
var DialogueLinkWidget = class extends import_view.WidgetType {
  constructor(linkText, exists, plugin) {
    super();
    this.linkText = linkText;
    this.exists = exists;
    this.plugin = plugin;
  }
  toDOM() {
    const container = document.createElement("span");
    container.className = "dialogue-link-widget";
    container.style.display = "inline-flex";
    container.style.alignItems = "center";
    container.style.gap = "4px";
    container.style.marginLeft = "4px";
    if (this.exists) {
      const navBtn = document.createElement("button");
      navBtn.textContent = "\u2192";
      navBtn.className = "dialogue-btn dialogue-nav-btn";
      navBtn.title = "Go to dialogue";
      navBtn.onclick = (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.plugin.openDialogue(this.linkText);
      };
      container.appendChild(navBtn);
      const deleteBtn = document.createElement("button");
      deleteBtn.textContent = "-";
      deleteBtn.className = "dialogue-btn dialogue-delete-btn";
      deleteBtn.title = "Delete dialogue";
      deleteBtn.onclick = (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.plugin.deleteDialogue(this.linkText);
      };
      container.appendChild(deleteBtn);
    } else {
      const createBtn = document.createElement("button");
      createBtn.textContent = "+";
      createBtn.className = "dialogue-btn dialogue-create-btn";
      createBtn.title = "Create dialogue";
      createBtn.onclick = (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.plugin.createDialogueFromLink(this.linkText);
      };
      container.appendChild(createBtn);
    }
    return container;
  }
  eq(other) {
    return this.linkText === other.linkText && this.exists === other.exists;
  }
};
function buildDecorations(state, plugin) {
  const builder = new import_state.RangeSetBuilder();
  const text = state.doc.toString();
  const regex = /\|DIA\|\[\[([^\]]+)\]\]/g;
  let match;
  while ((match = regex.exec(text)) !== null) {
    const linkText = match[1];
    const from = match.index + match[0].length;
    const exists = plugin.fileExists(linkText);
    const widget = new DialogueLinkWidget(linkText, exists, plugin);
    builder.add(from, from, import_view.Decoration.widget({
      widget,
      side: 1
    }));
  }
  return builder.finish();
}
function createDialogueExtension(plugin) {
  const dialogueField = import_state.StateField.define({
    create(state) {
      return buildDecorations(state, plugin);
    },
    update(oldSet, tr) {
      if (!tr.docChanged) {
        return oldSet.map(tr.changes);
      }
      return buildDecorations(tr.state, plugin);
    },
    provide(field) {
      return import_view.EditorView.decorations.from(field);
    }
  });
  return dialogueField;
}
var StartDialogueModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.characterName = "";
    this.dialogueName = "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Start New Dialogue Chain" });
    new import_obsidian.Setting(contentEl).setName("Character Name").setDesc("The character this dialogue is for").addText(
      (text) => text.onChange((value) => {
        this.characterName = value;
      })
    );
    new import_obsidian.Setting(contentEl).setName("Bundle Name").setDesc("Becomes (BundleName)_0)").addText(
      (text) => text.onChange((value) => {
        this.dialogueName = value;
      })
    );
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Create").setCta().onClick(() => {
        if (!this.characterName || !this.dialogueName) {
          new import_obsidian.Notice("Please fill in all fields");
          return;
        }
        this.onSubmit(this.characterName, this.dialogueName);
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AddOptionModal = class extends import_obsidian.Modal {
  constructor(app, defaultBundleName, onSubmit) {
    super(app);
    this.optionName = "";
    this.optionText = "";
    this.defaultBundleName = "";
    this.defaultBundleName = defaultBundleName;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Add Dialogue Option" });
    new import_obsidian.Setting(contentEl).setName("Bundle Name").setDesc("").addText((text) => {
      text.setValue(this.defaultBundleName);
      text.onChange((value) => {
        this.optionName = value;
      });
    });
    new import_obsidian.Setting(contentEl).setName("Display Name").setDesc("Player see this text.").addText(
      (text) => text.onChange((value) => {
        this.optionText = value;
      })
    );
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Add Option").setCta().onClick(() => {
        if (!this.optionName || !this.optionText) {
          new import_obsidian.Notice("Please fill in all fields");
          return;
        }
        this.onSubmit(this.optionName, this.optionText);
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var DialoguePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addStyles();
    this.registerEditorExtension(createDialogueExtension(this));
    this.addRibbonIcon("message-square", "Start New Dialogue", () => {
      new StartDialogueModal(this.app, (characterName, dialogueName) => {
        this.startNewDialogueChain(characterName, dialogueName);
      }).open();
    });
    this.addCommand({
      id: "start-new-dialogue",
      name: "Start New Dialogue Chain",
      callback: () => {
        new StartDialogueModal(this.app, (characterName, dialogueName) => {
          this.startNewDialogueChain(characterName, dialogueName);
        }).open();
      }
    });
    this.addCommand({
      id: "add-dialogue-option",
      name: "Add Dialogue Option",
      editorCallback: (editor, view) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (!activeFile) {
          new import_obsidian.Notice("No active file");
          return;
        }
        const content = editor.getValue();
        const currentBundle = this.extractBundle(content) || activeFile.basename;
        const existingOptions = this.countExistingOptions(content);
        const nextOptionNumber = existingOptions + 1;
        const defaultBundleName = `${currentBundle}_${nextOptionNumber}`;
        new AddOptionModal(this.app, defaultBundleName, (optionName, optionText) => {
          this.addDialogueOption(editor, optionName, optionText);
        }).open();
      }
    });
  }
  onunload() {
    this.removeStyles();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ==================== FILE OPERATIONS ====================
  fileExists(linkText) {
    const file = this.app.metadataCache.getFirstLinkpathDest(linkText, "");
    return file !== null;
  }
  async openDialogue(linkText) {
    const file = this.app.metadataCache.getFirstLinkpathDest(linkText, "");
    if (file) {
      await this.app.workspace.openLinkText(linkText, "", false);
    } else {
      new import_obsidian.Notice(`Dialogue "${linkText}" not found`);
    }
  }
  async deleteDialogue(linkText) {
    const confirmed = confirm(`Are you sure you want to delete "${linkText}"?

This will delete the file and remove the link from the parent note.`);
    if (!confirmed)
      return;
    const file = this.app.metadataCache.getFirstLinkpathDest(linkText, "");
    if (file && file instanceof import_obsidian.TFile) {
      const activeFile = this.app.workspace.getActiveFile();
      try {
        await this.app.vault.delete(file);
        if (activeFile) {
          await this.removeLinkFromParent(activeFile, linkText);
        }
        new import_obsidian.Notice(`Deleted dialogue: ${linkText}`);
      } catch (e) {
        new import_obsidian.Notice(`Error deleting dialogue: ${e}`);
      }
    } else {
      new import_obsidian.Notice(`Dialogue "${linkText}" not found`);
    }
  }
  async removeLinkFromParent(parentFile, linkText) {
    const content = await this.app.vault.read(parentFile);
    const lines = content.split("\n");
    const filteredLines = lines.filter((line) => !line.includes(`|DIA|[[${linkText}]]`));
    const updatedContent = filteredLines.join("\n");
    if (content !== updatedContent) {
      await this.app.vault.modify(parentFile, updatedContent);
    }
  }
  // ==================== DIALOGUE CREATION ====================
  async startNewDialogueChain(characterName, dialogueName) {
    var _a;
    const characterFileName = `${characterName} - Profile`;
    const characterFile = this.findFileRecursively(`${characterFileName}.md`);
    if (!characterFile) {
      new import_obsidian.Notice(`Character profile "${characterFileName}.md" not found. Make sure the file exists.`);
      return;
    }
    const characterFolder = ((_a = characterFile.parent) == null ? void 0 : _a.path) || "";
    const dialoguesFolder = characterFolder ? `${characterFolder}/Dialogues` : "Dialogues";
    const dialogueChainFolder = `${dialoguesFolder}/${dialogueName}`;
    try {
      await this.app.vault.createFolder(dialogueChainFolder);
    } catch (e) {
    }
    const fileName = `${dialogueName}_0`;
    const filePath = `${dialogueChainFolder}/${fileName}.md`;
    const template = await this.getTemplate();
    const content = this.fillTemplate(template, {
      date: new Date().toISOString().split("T")[0],
      root: `[[${characterFileName}]]`,
      characters: characterName,
      bundle: `${dialogueName}_0`
    });
    try {
      await this.app.vault.create(filePath, content);
      if (characterFile instanceof import_obsidian.TFile) {
        await this.addLinkToCharacterProfile(characterFile, fileName);
      }
      await this.app.workspace.openLinkText(filePath, "", false);
      new import_obsidian.Notice(`Created dialogue: ${fileName}`);
    } catch (e) {
      new import_obsidian.Notice(`Error creating dialogue: ${e}`);
    }
  }
  async createDialogueFromLink(linkText) {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian.Notice("No active file");
      return;
    }
    const pathParts = activeFile.path.split("/");
    const currentFolder = pathParts.slice(0, -1).join("/");
    let targetFolder;
    if (currentFolder.includes("/Dialogues/")) {
      targetFolder = currentFolder;
    } else {
      targetFolder = `${currentFolder}/Dialogues`;
      try {
        await this.app.vault.createFolder(targetFolder);
      } catch (e) {
      }
    }
    const filePath = `${targetFolder}/${linkText}.md`;
    const parentContent = await this.app.vault.read(activeFile);
    const characters = this.extractCharacters(parentContent);
    const root = this.extractRoot(parentContent);
    const template = await this.getTemplate();
    const content = this.fillTemplate(template, {
      date: new Date().toISOString().split("T")[0],
      root: root || `[[${activeFile.basename}]]`,
      prev: `[[${activeFile.basename}]]`,
      characters: characters.join(", "),
      bundle: linkText
    });
    try {
      await this.app.vault.create(filePath, content);
      await this.updateParentOptions(activeFile, linkText);
      await this.app.workspace.openLinkText(filePath, "", false);
      new import_obsidian.Notice(`Created dialogue: ${linkText}`);
    } catch (e) {
      new import_obsidian.Notice(`Error creating dialogue: ${e}`);
    }
  }
  async addDialogueOption(editor, optionName, optionText) {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian.Notice("No active file");
      return;
    }
    const baseName = activeFile.basename;
    const existingOptions = this.countExistingOptions(editor.getValue());
    const optionNumber = existingOptions + 1;
    const linkName = `${baseName}_${optionNumber}`;
    const content = editor.getValue();
    const optionsMatch = content.match(/\*\*Options\*\*[\s\S]*?(?=\n\*\*|$)/);
    if (optionsMatch) {
      const insertPos = optionsMatch.index + optionsMatch[0].length;
      const newOption = `
- |DIA|[[${linkName}]] : ${optionText}`;
      editor.replaceRange(newOption, editor.offsetToPos(insertPos));
    } else {
      const newSection = `

**Options**
- |DIA|[[${linkName}]] : ${optionText}`;
      editor.replaceRange(newSection, { line: editor.lastLine(), ch: editor.getLine(editor.lastLine()).length });
    }
    new import_obsidian.Notice(`Added option: ${optionName}`);
  }
  // ==================== FILE SEARCH ====================
  findFileRecursively(filename) {
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      if (file.name === filename || file.path.endsWith(`/${filename}`)) {
        return file;
      }
    }
    return null;
  }
  // ==================== HELPERS ====================
  async getTemplate() {
    try {
      const templateFile = this.app.vault.getAbstractFileByPath(this.settings.templatePath);
      if (templateFile instanceof import_obsidian.TFile) {
        return await this.app.vault.read(templateFile);
      }
    } catch (e) {
    }
    return `---
Date_Created: {{DATE}}
---


*Dialogue Root* : {{ROOT}}
*Previous Node* : {{PREV}}
# Characters: {{CHARACTERS}}
## Bundle : {{BUNDLE}}

CharacterName: Example words...

**Options**
- |DIA|[[Option1Name]]


`;
  }
  fillTemplate(template, data) {
    let result = template;
    for (const [key, value] of Object.entries(data)) {
      result = result.replace(new RegExp(`{{${key.toUpperCase()}}}`, "g"), value);
    }
    return result;
  }
  extractCharacters(content) {
    const match = content.match(/# Characters:\s*(.+)/);
    if (match) {
      return match[1].split(",").map((c) => c.trim());
    }
    return [];
  }
  extractRoot(content) {
    const match = content.match(/\*Dialogue Root\*\s*:\s*(.+)/);
    return match ? match[1].trim() : null;
  }
  extractBundle(content) {
    const match = content.match(/## Bundle\s*:\s*(.+)/);
    return match ? match[1].trim() : null;
  }
  countExistingOptions(content) {
    const optionsMatch = content.match(/\*\*Options\*\*/);
    if (!optionsMatch)
      return 0;
    const optionsSection = content.substring(optionsMatch.index);
    const optionLines = optionsSection.match(/^- /gm);
    return optionLines ? optionLines.length : 0;
  }
  async addLinkToCharacterProfile(characterFile, dialogueName) {
    const content = await this.app.vault.read(characterFile);
    const headerMatch = content.match(/# Character Dialogue[s]?/i);
    if (headerMatch) {
      const insertPos = headerMatch.index + headerMatch[0].length;
      const newLink = `
- |DIA|[[${dialogueName}]]`;
      if (!content.includes(`|DIA|[[${dialogueName}]]`)) {
        await this.app.vault.modify(
          characterFile,
          content.slice(0, insertPos) + newLink + content.slice(insertPos)
        );
      }
    } else {
      const newSection = `

--- 
# Character Dialogue
- |DIA|[[${dialogueName}]]`;
      await this.app.vault.modify(characterFile, content + newSection);
    }
  }
  async updateParentOptions(parentFile, linkText) {
    const content = await this.app.vault.read(parentFile);
    const updatedContent = content.replace(
      new RegExp(`- \\|DIA\\|\\[\\[${linkText}\\]\\]`, "g"),
      `- |DIA|[[${linkText}]]`
    );
    if (content !== updatedContent) {
      await this.app.vault.modify(parentFile, updatedContent);
    }
  }
  // ==================== STYLES ====================
  addStyles() {
    const style = document.createElement("style");
    style.id = "dialogue-plugin-styles";
    style.textContent = `
			.dialogue-link-widget {
				display: inline-flex !important;
				align-items: center;
				gap: 4px;
				margin-left: 4px;
				vertical-align: middle;
			}
			
			.dialogue-btn {
				background: var(--interactive-accent);
				color: var(--text-on-accent);
				border: none;
				border-radius: 4px;
				padding: 2px 6px;
				font-size: 12px;
				cursor: pointer;
				line-height: 1;
				min-width: 20px;
				height: 20px;
				display: flex;
				align-items: center;
				justify-content: center;
				transition: opacity 0.2s;
			}
			
			.dialogue-btn:hover {
				opacity: 0.8;
			}
			
			.dialogue-nav-btn {
				background: var(--interactive-success);
			}
			
			.dialogue-create-btn {
				background: var(--interactive-accent);
			}
			
			.dialogue-delete-btn {
				background: var(--text-error);
			}
		`;
    document.head.appendChild(style);
  }
  removeStyles() {
    const style = document.getElementById("dialogue-plugin-styles");
    if (style) {
      style.remove();
    }
  }
};
